name: Build & Publish 11ty Site
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js current
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          # publish_dir is the folder on the docker instance which eleventy builds the pages to.
          # it is not the docs folder in the repository
          publish_dir: dist
          # publish_branch is the branch in the repository.
          # this is where you need to point GitHub pages
          publish_branch: gh-pages