name: Update Posts From Notion
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Use Node.js current
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies & run notion
        run: |
          npm ci
          npm run notion

      - name: Commit & push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add posts
          git commit -m "Update posts from Notion"
          git push