name: Update Posts From Notion
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Use Node.js current
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies & run notion
        run: |
          touch .env
          echo NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} >> .env
          echo NOTION_DATABASE_ID=${{ env.NOTION_DATABASE_ID }} >> .env
          npm ci
          npm run notion

      - name: Commit & push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add posts
          git commit -m "Update posts from Notion"
          git push